---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  template:
    spec:
      containers:
      - name: server
        env:
        - name: SETTING1
          value: "blah1"
        - name: SETTING2
          value: "blah2" 